import type { Metadata } from "next";
import "../styles/globals.css";

import ThemeProvider from "@/components/layout/ThemesProvider";
import Head from "next/head";
import MainNav from "@/components/layout/MainNav";

export const metadata: Metadata = {
  title: "Anna Wain's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          href="/favicon-180x180.png"
          sizes="180x180"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
      </Head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="w-full">
            <MainNav />
          </nav>
          <main className="flex flex-col">
            <div className="w-fullh-[100vh] overflow-hidden">{children}</div>
          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center"></footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
